=== Blask0/xp/modules/wem-api/src/main/resources/com/enonic/wem/api/xml/schema/model.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="content-type" type="contentType"/>
    <xs:element name="form" type="form"/>
    <xs:element name="image-component" type="imageDescriptor"/>
    <xs:element name="layout-component" type="layoutDescriptor"/>
    <xs:element name="metadata-schema" type="metadataSchema"/>
    <xs:element name="mixin" type="mixin"/>
    <xs:element name="module" type="module"/>
    <xs:element name="node" type="node"/>
    <xs:element name="page-component" type="pageDescriptor"/>
    <xs:element name="part-component" type="partDescriptor"/>
    <xs:element name="relationship-type" type="relationshipType"/>
    <xs:complexType name="mixin">
        <xs:all>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="description" type="xs:string"/>
            <xs:element minOccurs="0" name="items" type="formItems"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="formItems">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="input" type="input"/>
                <xs:element name="mixin-reference" type="mixinReference"/>
                <xs:element name="field-set" type="fieldSet"/>
                <xs:element name="form-item-set" type="formItemSet"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="input">
        <xs:complexContent>
            <xs:extension base="formItem">
                <xs:sequence>
                    <xs:element minOccurs="0" name="label" type="xs:string"/>
                    <xs:element minOccurs="0" name="immutable" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="indexed" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="custom-text" type="xs:string"/>
                    <xs:element minOccurs="0" name="help-text" type="xs:string"/>
                    <xs:element minOccurs="0" name="validation-regexp" type="xs:string"/>
                    <xs:element minOccurs="0" name="occurrences" type="occurrence"/>
                    <xs:element minOccurs="0" name="config" type="xs:anyType"/>
                </xs:sequence>
                <xs:attribute name="type" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="true" name="formItem">
        <xs:sequence/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="occurrence">
        <xs:sequence/>
        <xs:attribute name="minimum" type="xs:integer" use="required"/>
        <xs:attribute name="maximum" type="xs:integer" use="required"/>
    </xs:complexType>
    <xs:complexType name="formItemSet">
        <xs:complexContent>
            <xs:extension base="formItem">
                <xs:sequence>
                    <xs:element minOccurs="0" name="label" type="xs:string"/>
                    <xs:element minOccurs="0" name="immutable" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="custom-text" type="xs:string"/>
                    <xs:element minOccurs="0" name="help-text" type="xs:string"/>
                    <xs:element minOccurs="0" name="occurrences" type="occurrence"/>
                    <xs:element minOccurs="0" name="items" type="formItems"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="mixinReference">
        <xs:complexContent>
            <xs:extension base="formItem">
                <xs:sequence>
                    <xs:element name="reference" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="fieldSet">
        <xs:complexContent>
            <xs:extension base="formItem">
                <xs:sequence>
                    <xs:element minOccurs="0" name="label" type="xs:string"/>
                    <xs:element minOccurs="0" name="items" type="formItems"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="form">
        <xs:complexContent>
            <xs:extension base="formItems">
                <xs:sequence/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="layoutDescriptor">
        <xs:all>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="form"/>
            <xs:element minOccurs="0" name="regions" type="regionsDescriptor"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="regionsDescriptor">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0"
                name="region" type="regionDescriptor"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="regionDescriptor">
        <xs:sequence/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="partDescriptor">
        <xs:all>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="form"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="node">
        <xs:all>
            <xs:element minOccurs="0" name="id" type="xs:string"/>
            <xs:element minOccurs="0" name="created-time" type="xs:dateTime"/>
            <xs:element minOccurs="0" name="modified-time" type="xs:dateTime"/>
            <xs:element minOccurs="0" name="creator" type="xs:string"/>
            <xs:element minOccurs="0" name="modifier" type="xs:string"/>
            <xs:element minOccurs="0" name="data" type="dataSet"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="dataSet">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="property" type="dataProperty"/>
                <xs:element name="property-set" type="dataSet"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="dataProperty">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:string" use="required"/>
                <xs:attribute name="type" type="dataPropertyType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="imageDescriptor">
        <xs:all>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="form"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="pageDescriptor">
        <xs:all>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="form"/>
            <xs:element minOccurs="0" name="regions" type="regionsDescriptor"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="module">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="version" type="xs:string"/>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="url" type="xs:string"/>
            <xs:element minOccurs="0" name="vendor" type="vendor"/>
            <xs:element minOccurs="0" name="config" type="form"/>
            <xs:element minOccurs="0" name="metadata-schemas" type="metadata-schemas"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="vendor">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="url" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="metadata-schemas">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0"
                name="metadata-schema" type="metadataSchema"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="metadataSchema">
        <xs:sequence>
            <xs:element minOccurs="0" name="form" type="form"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="contentType">
        <xs:all>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="description" type="xs:string"/>
            <xs:element minOccurs="0" name="content-display-name-script" type="xs:string"/>
            <xs:element minOccurs="0" name="super-type" type="xs:string"/>
            <xs:element minOccurs="0" name="is-abstract" type="xs:boolean"/>
            <xs:element minOccurs="0" name="is-final" type="xs:boolean"/>
            <xs:element minOccurs="0" name="is-built-in" type="xs:boolean"/>
            <xs:element minOccurs="0" name="allow-child-content" type="xs:boolean"/>
            <xs:element minOccurs="0" name="form" type="formItems"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="relationshipType">
        <xs:all>
            <xs:element minOccurs="0" name="description" type="xs:string"/>
            <xs:element minOccurs="0" name="from-semantic" type="xs:string"/>
            <xs:element minOccurs="0" name="to-semantic" type="xs:string"/>
            <xs:element minOccurs="0" name="allowed-from-types" type="allowedTypesDescriptor"/>
            <xs:element minOccurs="0" name="allowed-to-types" type="allowedTypesDescriptor"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="allowedTypesDescriptor">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0"
                name="content-type" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="canRenderDescriptor">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0"
                name="content-type" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="pageRegions">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0"
                name="region" type="pageRegion"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="pageRegion">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0"
                name="part-component" type="partComponent"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="partComponent">
        <xs:all>
            <xs:element minOccurs="0" name="display-name" type="xs:string"/>
            <xs:element minOccurs="0" name="config" type="xs:anyType"/>
        </xs:all>
        <xs:attribute name="descriptor" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="contentFilter">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="deny" type="xs:string"/>
                <xs:element name="allow" type="xs:string"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="dataPropertyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Data"/>
            <xs:enumeration value="HtmlPart"/>
            <xs:enumeration value="Double"/>
            <xs:enumeration value="Long"/>
            <xs:enumeration value="Xml"/>
            <xs:enumeration value="LocalDate"/>
            <xs:enumeration value="LocalDateTime"/>
            <xs:enumeration value="LocalTime"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="ContentId"/>
            <xs:enumeration value="GeoPoint"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Blask0/xp/modules/wem-api/src/main/resources/com/enonic/wem/api/xml/examples/module.xml
<?xml version="1.0" encoding="UTF-8" ?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/model.xsd">

  <name>mymodule</name>
  <version>1.0.0</version>
  <display-name>My Test Module</display-name>

  <vendor>
    <name>Enonic</name>
    <url>http://www.enonic.com</url>
  </vendor>

  <config>
    <mixin-reference name="test">
      <reference>mymodule-1.0.0:other</reference>
    </mixin-reference>
  </config>

  <metadata-schemas>
    <metadata-schema name="menu">
      <form>
        <input name="show" type="Boolean"/>
      </form>
    </metadata-schema>
  </metadata-schemas>

</module>

=== Blask0/xp/modules/core-api/src/main/xsd/examples/image-descriptor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<image-component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../model.xsd">
  <display-name>An Image</display-name>
  <config>
    <input name="width" type="Double">
      <label>Column width</label>
      <immutable>false</immutable>
      <indexed>false</indexed>
      <occurrences minimum="0" maximum="1"/>
    </input>
  </config>
</image-component>

=== Blask0/xp/modules/wem-api/src/main/resources/com/enonic/wem/api/xml/examples/page-descriptor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<page-component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/model.xsd">
  <display-name>Landing page</display-name>
  <config>
    <input name="pause" type="DecimalNumber">
      <label>Pause parameter</label>
      <immutable>false</immutable>
      <indexed>false</indexed>
      <occurrences minimum="0" maximum="1"/>
    </input>
    <form-item-set name="myFormItemSet">
      <label>My form item set</label>
      <items>
        <input name="myTextLine" type="TextLine">
          <label>My text line</label>
          <immutable>false</immutable>
          <indexed>false</indexed>
          <occurrences minimum="1" maximum="1"/>
        </input>
        <input name="myCustomInput" type="TextLine">
          <label>My custom input</label>
          <immutable>false</immutable>
          <indexed>false</indexed>
          <occurrences minimum="0" maximum="1"/>
        </input>
        <field-set name="myFieldSet">
          <label>My field set</label>
          <items>
            <input name="fieldSetItem" type="TextLine">
              <label>Field set Item</label>
              <immutable>false</immutable>
              <indexed>false</indexed>
              <occurrences minimum="0" maximum="1"/>
            </input>
          </items>
        </field-set>
      </items>
      <immutable>false</immutable>
      <occurrences minimum="0" maximum="1"/>
    </form-item-set>
  </config>
  <regions>
    <region name="header"/>
    <region name="main"/>
    <region name="footer"/>
  </regions>
</page-component>

=== Blask0/xp/modules/core-api/src/main/xsd/examples/layout-descriptor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<layout-component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../model.xsd">
  <display-name>A Layout</display-name>
  <config>
    <input name="width" type="Double">
      <label>Column width</label>
      <immutable>false</immutable>
      <indexed>false</indexed>
      <occurrences minimum="0" maximum="1"/>
    </input>
  </config>
  <regions>
    <region name="left"/>
    <region name="right"/>
  </regions>
</layout-component>

=== Blask0/xp/modules/core-api/src/main/resources/com/enonic/wem/api/xml/examples/relationship-type.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<relationship-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/model.xsd">
  <description>description</description>
  <from-semantic>likes</from-semantic>
  <to-semantic>liked by</to-semantic>
  <allowed-from-types>
    <content-type>mymodule-1.0.0:animal</content-type>
    <content-type>mymodule-1.0.0:person</content-type>
  </allowed-from-types>
  <allowed-to-types>
    <content-type>mymodule-1.0.0:vehicle</content-type>
  </allowed-to-types>
</relationship-type>

=== Blask0/xp/modules/core-api/src/main/resources/com/enonic/wem/api/xml/examples/node.xml
<?xml version="1.0" encoding="UTF-8" ?>
<node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/model.xsd">
  <id>f95b70fdc3088560732a5ac135644506</id>
  <created-time>2008-09-29T03:49:45</created-time>
  <modified-time>2014-09-19T01:18:33</modified-time>
  <creator>user:system:admin</creator>
  <modifier>user:system:admin</modifier>

  <data name="data">
    <property name="display-name" type="String">Fisk</property>
    <property name="content-type" type="String">com.enonic.system:article</property>
    <property name="draft" type="Boolean">false</property>
    <property-set name="form">
      <property-set name="Input">
        <property name="name" type="String">textline</property>
        <property name="label" type="String">Text Line</property>
        <property name="customText" type="String">customText</property>
        <property name="helpText" type="String">Some help text</property>
        <property name="immutable" type="String">false</property>
        <property name="indexed" type="Boolean">true</property>

        <property-set name="occurrences">
          <property name="minimum" type="Long">0</property>
          <property name="maximum" type="Long">1</property>
        </property-set>

      </property-set>

    </property-set>

  </data>
</node>

=== Blask0/xp/modules/core-api/src/main/resources/com/enonic/wem/api/xml/examples/part-descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<part-component xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/model.xsd">
  <display-name>A Part</display-name>
  <config>
    <input name="width" type="Double">
      <label>Column width</label>
      <immutable>false</immutable>
      <indexed>false</indexed>
      <occurrences minimum="0" maximum="1"/>
    </input>
  </config>
</part-component>
